#define str_EPERM "Operation not permitted "
#define str_ENOENT "No such file or directory "
#define str_ESRCH "No such process "
#define str_EINTR "Interrupted system call "
#define str_EIO "I/O error "
#define str_ENXIO "No such device or address "
#define str_E2BIG "Argument list too long "
#define str_ENOEXEC "Exec format error "
#define str_EBADF "Bad file number "
#define str_ECHILD "No child processes "
#define str_EAGAIN "Try again "
#define str_ENOMEM "Out of memory "
#define str_EACCES "Permission denied "
#define str_EFAULT "Bad address "
#define str_ENOTBLK "Block device required "
#define str_EBUSY "Device or resource busy "
#define str_EEXIST "File exists "
#define str_EXDEV "Cross-device link "
#define str_ENODEV "No such device "
#define str_ENOTDIR "Not a directory "
#define str_EISDIR "Is a directory "
#define str_EINVAL "Invalid argument "
#define str_ENFILE "File table overflow "
#define str_EMFILE "Too many open files "
#define str_ENOTTY "Not a typewriter "
#define str_ETXTBSY "Text file busy "
#define str_EFBIG "File too large "
#define str_ENOSPC "No space left on device "
#define str_ESPIPE "Illegal seek "
#define str_EROFS "Read-only file system "
#define str_EMLINK "Too many links "
#define str_EPIPE "Broken pipe "
#define str_EDOM "Math argument out of domain of func "
#define str_ERANGE "Math result not representable "
#define str_EDEADLK "Resource deadlock would occur "
#define str_ENAMETOOLONG "File name too long "
#define str_ENOLCK "No record locks available "
#define str_ENOSYS "Function not implemented "
#define str_ENOTEMPTY "Directory not empty "
#define str_ELOOP "Too many symbolic links encountered "
#define str_EWOULDBLOCK "Operation would block "
#define str_ENOMSG "No message of desired type "
#define str_EIDRM "Identifier removed "
#define str_ECHRNG "Channel number out of range "
#define str_EL2NSYNC "Level 2 not synchronized "
#define str_EL3HLT "Level 3 halted "
#define str_EL3RST "Level 3 reset "
#define str_ELNRNG "Link number out of range "
#define str_EUNATCH "Protocol driver not attached "
#define str_ENOCSI "No CSI structure available "
#define str_EL2HLT "Level 2 halted "
#define str_EBADE "Invalid exchange "
#define str_EBADR "Invalid request descriptor "
#define str_EXFULL "Exchange full "
#define str_ENOANO "No anode "
#define str_EBADRQC "Invalid request code "
#define str_EBADSLT "Invalid slot "
#define str_EBFONT "Bad font file format "
#define str_ENOSTR "Device not a stream "
#define str_ENODATA "No data available "
#define str_ETIME "Timer expired "
#define str_ENOSR "Out of streams resources "
#define str_ENONET "Machine is not on the network "
#define str_ENOPKG "Package not installed "
#define str_EREMOTE "Object is remote "
#define str_ENOLINK "Link has been severed "
#define str_EADV "Advertise error "
#define str_ESRMNT "Srmount error "
#define str_ECOMM "Communication error on send "
#define str_EPROTO "Protocol error "
#define str_EMULTIHOP "Multihop attempted "
#define str_EDOTDOT "RFS specific error "
#define str_EBADMSG "Not a data message "
#define str_EOVERFLOW "Value too large for defined data type "
#define str_ENOTUNIQ "Name not unique on network "
#define str_EBADFD "File descriptor in bad state "
#define str_EREMCHG "Remote address changed "
#define str_ELIBACC "Can not access a needed shared library "
#define str_ELIBBAD "Accessing a corrupted shared library "
#define str_ELIBSCN ".lib section in a.out corrupted "
#define str_ELIBMAX "Attempting to link in too many shared libraries "
#define str_ELIBEXEC "Cannot exec a shared library directly "
#define str_EILSEQ "Illegal byte sequence "
#define str_ERESTART "Interrupted system call should be restarted "
#define str_ESTRPIPE "Streams pipe error "
#define str_EUSERS "Too many users "
#define str_ENOTSOCK "Socket operation on non-socket "
#define str_EDESTADDRREQ "Destination address required "
#define str_EMSGSIZE "Message too long "
#define str_EPROTOTYPE "Protocol wrong type for socket "
#define str_ENOPROTOOPT "Protocol not available "
#define str_EPROTONOSUPPORT "Protocol not supported "
#define str_ESOCKTNOSUPPORT "Socket type not supported "
#define str_EOPNOTSUPP "Operation not supported on transport endpoint "
#define str_EPFNOSUPPORT "Protocol family not supported "
#define str_EAFNOSUPPORT "Address family not supported by protocol "
#define str_EADDRINUSE "Address already in use "
#define str_EADDRNOTAVAIL "Cannot assign requested address "
#define str_ENETDOWN "Network is down "
#define str_ENETUNREACH "Network is unreachable "
#define str_ENETRESET "Network dropped connection because of reset "
#define str_ECONNABORTED "Software caused connection abort "
#define str_ECONNRESET "Connection reset by peer "
#define str_ENOBUFS "No buffer space available "
#define str_EISCONN "Transport endpoint is already connected "
#define str_ENOTCONN "Transport endpoint is not connected "
#define str_ESHUTDOWN "Cannot send after transport endpoint shutdown "
#define str_ETOOMANYREFS "Too many references: cannot splice "
#define str_ETIMEDOUT "Connection timed out "
#define str_ECONNREFUSED "Connection refused "
#define str_EHOSTDOWN "Host is down "
#define str_EHOSTUNREACH "No route to host "
#define str_EALREADY "Operation already in progress "
#define str_EINPROGRESS "Operation now in progress "
#define str_ESTALE "Stale NFS file handle "
#define str_EUCLEAN "Structure needs cleaning "
#define str_ENOTNAM "Not a XENIX named type file "
#define str_ENAVAIL "No XENIX semaphores available "
#define str_EISNAM "Is a named type file "
#define str_EREMOTEIO "Remote I/O error "
#define str_EDQUOT "Quota exceeded "
#define str_ENOMEDIUM "No medium found "
#define str_EMEDIUMTYPE "Wrong medium type "
